config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  resources :docs
  authenticated :user do
    root "docs#index", as: "authenticated_root"
  end
  root 'welcome#index'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doc.rb
class Doc < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :docs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  before_action :find_doc, only: [:show, :edit, :update, :destroy]
  def index
    @docs = Doc.where(user_id: current_user)
  end

  def show

  end

  def new
    @doc = current_user.docs.build
  end

  def create
    @doc = current_user.docs.build(doc_params)
    if @doc.save
      redirect_to @doc
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @doc.update(doc_params)
      redirect_to @doc
    else
      render 'edit'
    end
  end

  def destroy
    @doc.destroy
    redirect_to docs_path
  end

  private

    def find_doc
      @doc = Doc.find(params[:id])
    end

    def doc_params
      params.require(:doc).permit(:title, :content)

    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/docs/_form.html.erb
<%= simple_form_for @doc do |f| %>
  <%= f.input :title %>
  <%= f.input :content %>
  <%= f.button :submit, class: "button" %>
<% end %>

app/views/docs/edit.html.erb
<div class="wrapper_with_padding">
  <h1>Fix Doc!</h1>
  <%= render 'form' %>
  <%= link_to "Cancel", doc_path %>
</div>

app/views/docs/index.html.erb
<div class="wrapper_with_padding">
  <div class="clearfix" id="docs">
    <% unless @docs.blank? %>
      <% @docs.each do |doc| %>
        <a href="<%= (url_for [doc]) %>">
          <div class="doc">
            <p class="title"><%= doc.title %></p>
            <p class="date"><%= time_ago_in_words(doc.created_at) %></p>
            <p class="content"><%= truncate(doc.content, length:50) %></p>
          </div>
        </a>
      <% end %>
    <% else %>
      <h2>Create Doc</h2>
      <p>Start Creating Documents and Organizing Your Life!</p>
      <button><%= link_to "Create Doc", new_doc_path %></button>
    <% end %>
  </div>
</div>
<%= link_to "Create Doc", new_doc_path %>

app/views/docs/new.html.erb
<div class="wrapper_with_padding">
  <h1> New Doc! </h1>
  <%= render 'form' %>
</div>

app/views/docs/show.html.erb
<div class="wrapper_with_padding">
  <div id="doc_show">
    <h1 class="title"><%= @doc.title %></h1>
    <p><%= simple_format(@doc.content) %></p>
    <div class="buttons">
      <%= link_to "Fix Doc", edit_doc_path(@doc), class: "button" %>
      <%= link_to "Trash It", doc_path(@doc), method: :delete, data:
          {confirm: "Are you sure?" }, class: "button" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
  <title>FileCabinet | Your life's work!</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <div class="header_inner"><%= link_to "FileCabinet", root_path, id: "logo" %>
      <nav>
        <% if user_signed_in? %>
          <%= link_to "Create Doc", new_doc_path %>
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>

        <% else %>
          <%= link_to "Log In", new_user_session_path %>
        <% end %>
      </nav>
    </div>

  </header>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
</body>
</html>

app/views/welcome/index.html.erb
<div id="banner">
  <div class="banner_content">
    <h1>File Cabinet</h1>
    <p>Your life's work. Organized, always.</p>
    <button>
      <%= link_to "Enter", new_user_registration_path %>
    </button>
  </div>
</div>
<div id="callouts">
  <div class="callout_inner">
    <div class="wrapper">
      <div class="callout">
        <h2>Organize</h2>
        <p>Lorem ipsum dolor amet twee whatever plaid distillery </p>
      </div>
    </div>
  </div>
</div>
<div id="bottom_cta">
  <div class="wrapper">
    <h2>Go Ahead!</h2>
    <br/>
    <button><%= link_to "Join Now", new_user_registration_path %></button>
  </div>
</div>